Optimistic-Worms/basket-bear

client/components/Product.jsx, client/components/Search.jsx, client/components/SearchList.jsx, server/server.js
-Also added parse search results function that takes what data we want to save from the ebay results and creates a new object out of it
-Each search result also now includes the button to go buy the product on ebay
=> Implemented Client Search Function & Search List to display list of Search Results

client/components/Search.jsx, server/server.js
encode multi word queries
skip products that dont have a medium image or list price
=> fixed amazon search

__tests__/server.test.js, client/components/Search.jsx, client/components/user/LoginCard.jsx, client/components/user/firebase-auth.js, package-lock.json, server/controllers/shoppingList.js, server/server.js
-When clicking add to shopping list button for a product, it saves the product to the user's shopping list. The first time trying to add a product, it creates a new shopping list for the user.  Doesn't add item to shopping list if the user is not logged in.
-Moved firebase auth config to a separate file (out of the login component) so it can be used in other components.
-Deleted server tests because they are not configured to the new route functions.
=> Implemented Shopping List Functions

client/components/App.jsx, client/components/Navbar.jsx, client/components/Product.jsx, client/components/Search.jsx, client/components/SearchList.jsx, client/components/ShoppingList.jsx, client/components/ShoppingListItem.jsx, package-lock.json, server/controllers/shoppingList.js, server/server.js
-User can add or remove items from their shopping list
-User is alerted when trying to add an item, if they are not signed in
-Shopping list automatically updates when an item is removed
=> Shopping List Display and Functions

client/components/Navbar.jsx, client/components/Search.jsx, client/components/ShoppingList.jsx, client/components/user/LoginCard.jsx, client/components/user/ManualUser.jsx, client/css/styles.css
-fixed some bugs
-edited css
-redirect users to home page after logging in
-display alert on page rather than popup when trying to view watch list without being logged in
=> Fixed functions for login and shopping list

client/components/Info.jsx, client/components/ShoppingList.jsx, client/components/ShoppingListItem.jsx, client/css/styles.css, package-lock.json
change background image to intro card background
fix bottom scroll from appearing
make footer solid
=> css updates

client/components/App.jsx, client/components/Navbar.jsx, client/components/Product.jsx, client/components/Search.jsx, client/components/ShoppingList.jsx, client/components/ShoppingListItem.jsx, client/components/user/GoogleUser.jsx, client/components/user/LoginCard.jsx, package-lock.json, server/controllers/amazonApiCalls.js, server/controllers/ebayApiCalls.js, server/controllers/shoppingList.js, server/server.js
-when user first logs in, updates Amazon prices with current price on user's watch list
-fixed amazon price listing (displays lowest sale price)
-moved amazon and ebay api logic to separate module outside of server
=> Major pricing fixes and additions

client/components/App.jsx, client/components/Info.jsx, client/components/Search.jsx, client/components/developer/ApiNav.jsx, client/components/developer/Developer.jsx, client/components/developer/DeveloperFooter.jsx, client/css/styles.css, package-lock.json
move search bar to intro card
add mobile responsive developer nav
update footer style
=> update mobile responsive style

client/components/App.jsx, server/controllers/amazonApiCalls.js, server/controllers/ebayApiCalls.js, server/server.js
-makes call to ebay shopping api to get current prices of items and updates watch list
-only works for max 10 ebay items plus 10 amazon items
=> Get eBay Item Current Price

client/components/App.jsx
-after user logs out, they can click login again
-only display sign up info if user is not logged in
=> fixed logged in issues

client/components/App.jsx, client/components/ShoppingList.jsx, client/components/user/priceLookup.js
=> Moved price lookup functions to separate module

client/components/App.jsx, client/components/Search.jsx, client/components/ShoppingList.jsx, client/components/user/priceLookup.js, server/server.js
-parse amazon results in separate function
-fixed pricing lookup
-fixed pricing when saving to shopping list
-reloads shopping list when browser is refreshed
=> Bug fixes and Shopping List reloading

client/components/ProductSettings.jsx, client/components/Search.jsx, client/components/ShoppingList.jsx, client/components/ShoppingListItem.jsx, server/controllers/ebayApiCalls.js, server/controllers/shoppingList.js, server/server.js
- displays message when ebay returns no results
- sets current price when adding ebay item to watch list
- user can set a watch price on items on their watch list
- adds product to a product collection when user adds the item to their watch list
=> Set Watch Price

client/components/ShoppingList.jsx
- Items on watch list are displayed in order of increasing current price
- Items stay at same position after each action
=> Sorts Watch List

client/components/ShoppingList.jsx, server/controllers/watchedItems.js, server/server.js
- add items to watch list collection
- remove items from watch list if no more users are watching
=> Watch list collection

client/components/user/sw.js, package-lock.json, server/server.js
- Email sender sends from budgetbasketinfo@gmail.com
- Email sender is restricted to about 200 emails a day - for dev
- Note: Sending large numbers of emails has a lot of difficulties to overcome
=> Add basic email send tool

client/components/ShoppingList.jsx, package-lock.json, server/controllers/watchedItems.js, server/helpers/amazon.js, server/server.js
- updates current prices on watched amazon AND ebay products
- logs a notification if current price has dropped below a user's watch price
=> watchedItems worker for Amazon and Ebay products

package-lock.json, server/controllers/notificationWorker.js, server/controllers/pushNotifications.js, server/controllers/watchedItems.js, server/server.js
- Moved subscribe and unsubscribe out of server
- Add simple email auth
=> Move subscribe and unsubscribe out of server

server/controllers/notificationWorker.js
- notification work loops throw awaitNotification data and send push notification
- requires call to endpoint at a trigger
=> add notification worker

client/src/index.jsx, server/controllers/product.js, server/helpers/productHelpers.js
- GET request with no parameters returns 100 most popular products sorted by number of user/price records. Product id's are included in the response
- GET request with id parameter returns product data for the matching id including average requested price
- GET request with name parameter returns any products that match all or part of a string
=> allow searching product db by name or id from /products endpoint

server/controllers/watchedItems.js
- checks if price has changed
- only updates price if changed
- only notifies users if price has dropped
=> Watched items worker

server/controllers/watchedItems.js
- must send get request with auth secret password
=> add authentication to watch item worker

server/controllers/notificationWorker.js, server/controllers/userSettings.js
- This will get things set up ready - but further optimization is required
=> Bear emailer - simple set up ready to test end point

client/components/user/priceLookup.js, server/controllers/watchedItems.js, server/helpers/amazon.js
- displays item is no longer available
- notify the user that product is no longer available
=> Handle if item is no longer available on Amazon

server/controllers/notificationWorker.js, server/controllers/userSettings.js
- Callback object includes data from all processes in the notification API.
=> Add callback object to notifications endpoint

client/components/ShoppingList.jsx, client/components/ShoppingListItem.jsx
-Sorts the items with current price below watch price to the top of the watch list
-Displays message if the current price is below watch price
-Unavailable items sort to the bottom of the list
-Displays message that item no longer available
=> Watch List Ordering

server/controllers/watchedItems.js
- separated functions and made them all return promises
- add promise arrays for watchListWorker, get products, send to amazon/ebay, and compare watch prices functions
- collects messages from all promises and returns then in the worker response when all are done executing
=> Watched Items Worker Response Messages

client/components/user/LoginCard.jsx, client/components/user/ManualUser.jsx, client/components/user/Settings.jsx, client/css/settings.css
- This makes sure a manual user signed up real email address in order to get full notification functionality.
=> add email verification to settings panel

client/components/user/ManualUser.jsx, client/components/user/Settings.jsx, server/controllers/authroutes.js, server/server.js
- cron routes will need a token when called
=> add secret authentication token to cron routes

server/controllers/emailNotifications.js, server/controllers/notificationWorker.js, server/server.js
- The mailer is set up ready and waiting for new limits approval from amazon.
- The mailer creds are in the .env document
=> Amazon emailer set up ready
